"""
MockAISProvider — the default position source.

Reads from the in-process voyage simulator rather than any external feed, so
SeaPath is fully demonstrable without an AIS subscription. Every fix it
returns is tagged `source="simulated"`, which propagates to the API response
and drives the "DEMO SIMULATION" badge in the UI.

This provider invents no vessel traffic: it reports only vessels that the
user has explicitly started a simulated voyage for.
"""
from __future__ import annotations

from typing import Optional

from app.services.ais.base import AISProvider, VesselFix
from app.services.simulation import simulation_registry


class MockAISProvider(AISProvider):
    name = "mock"
    simulated = True

    def get_vessel_position(self, vessel_id: int) -> Optional[VesselFix]:
        sim = simulation_registry.get_by_vessel(vessel_id)
        return sim.to_fix() if sim else None

    def get_vessels(self) -> list[VesselFix]:
        # one fix per vessel — the newest simulation wins if a vessel somehow
        # has more than one voyage loaded
        by_vessel: dict[int, VesselFix] = {}
        for sim in simulation_registry.all():
            by_vessel[sim.vessel_id] = sim.to_fix()
        return list(by_vessel.values())

    def describe(self) -> dict:
        return {
            "provider": self.name,
            "simulated": True,
            "label": "LIVE TRACKING — DEMO SIMULATION",
            "detail": (
                "Positions are generated by SeaPath's voyage simulator moving "
                "along the calculated route. They are not real AIS data."
            ),
        }
